[package]
name = "dir_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
figlet-rs = "0.1.4"
chrono = "0.4.23"